# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2022-03-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('CO', 'Comedy'), ('AC', 'Action'), ('DR', 'Drama'), ('HO', 'Horror')], max_length=2),
        ),
    ]
